redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  channel: "SkyCloud"

database:
  url: "jdbc:mysql://localhost:3306/development?characterEncoding=utf8"
  username: "admin"
  password: "admin2"

server:
  name: hub-1

utils:
  adminPerm: 'skycloud.admin'